//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampoIdioma
    {
        public int Id_Idioma { get; set; }
        public string Texto_Lbl { get; set; }
        public int Id_label { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual Label_Etiqueta Label_Etiqueta { get; set; }
    }
}
