//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteGYM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteGYM()
        {
            this.ClienteRutina = new HashSet<ClienteRutina>();
            this.Finanza = new HashSet<Finanza>();
        }
    
        public int Id_Cliente { get; set; }
        public int Id_Sucursal { get; set; }
        public int Id_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<double> PesoKg { get; set; }
        public int Id_Estado { get; set; }
        public Nullable<int> Dni { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> CodPostal { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteRutina> ClienteRutina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finanza> Finanza { get; set; }
    }
}
