//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteRutina
    {
        public int Id_Cliente { get; set; }
        public int Id_Ejercicio { get; set; }
        public string TiempoYDescripcion { get; set; }
    
        public virtual ClienteGYM ClienteGYM { get; set; }
        public virtual Ejercicio Ejercicio { get; set; }
    }
}
