//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finanza
    {
        public int Id_Finanza { get; set; }
        public Nullable<System.DateTime> UltimaFechaPagada { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Estado { get; set; }
    
        public virtual ClienteGYM ClienteGYM { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
