//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymAppEntities : DbContext
    {
        public GymAppEntities()
            : base("name=GymAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<CampoIdioma> CampoIdioma { get; set; }
        public virtual DbSet<ClienteGYM> ClienteGYM { get; set; }
        public virtual DbSet<ClienteRutina> ClienteRutina { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Finanza> Finanza { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Label_Etiqueta> Label_Etiqueta { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<PerfilPyF> PerfilPyF { get; set; }
        public virtual DbSet<PermisosRelacion> PermisosRelacion { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<DVV> DVV { get; set; }
    }
}
