//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosRelacion
    {
        public int Id_Perfil { get; set; }
        public int Id_Padre { get; set; }
    
        public virtual PerfilPyF PerfilPyF { get; set; }
    }
}
