//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.PerfilPyF = new HashSet<PerfilPyF>();
        }
    
        public string Rol { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public string DVH { get; set; }
        public Nullable<int> Id_Idioma { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public int Id_Usuario { get; set; }
        public Nullable<int> Id_Perfil { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Idioma Idioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilPyF> PerfilPyF { get; set; }
    }
}
